apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: web
  labels:
    type: back-end
spec:
  replicas: 1
  selector: 
     matchLabels: 
       type: back-end
  template:
     metadata:
        name: mysqlpod
        labels:
           type: back-end
     spec:
       containers:
       -  name: mysqlimage
          image: docker4ranjit/mysql:11
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                  name: my-config
            - secretRef:
                  name: my-secret
          volumeMounts:
           - name: myvol
             mountPath: /var/lib/mysql
       volumes:
       - name: myvol
         persistentVolumeClaim:
           claimName: mypvc

         