apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  namespace: web
spec:
  storageClassName: manual 
  accessModes:
     - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
     path: /tmp

