apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: web
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi    
