apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: web
  labels:
    type: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      name: mypod
      labels:
         type: front-end
    spec:
       containers: 
        - name: tomcat
          image: docker4ranjit/loginwebapp:11             